package com.rivetlogic.jobsboard.action;

import com.liferay.counter.service.CounterLocalServiceUtil;
import com.liferay.portal.kernel.events.ActionException;
import com.liferay.portal.kernel.events.SimpleAction;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.model.Role;
import com.liferay.portal.model.RoleConstants;
import com.liferay.portal.service.ClassNameLocalServiceUtil;
import com.liferay.portal.service.RoleLocalServiceUtil;
import com.liferay.portal.service.UserLocalServiceUtil;
import com.liferay.portal.util.PortalUtil;
import com.rivetlogic.jobsboard.util.FiltersUtil;

import java.util.Date;

public class JobsBoardStartupAction extends SimpleAction {

    private static final Log LOG = LogFactoryUtil.getLog(JobsBoardStartupAction.class);
    
    @Override
    public void run(String[] args) throws ActionException {
        LOG.debug("Running custom startup action");
        Long companyId = PortalUtil.getDefaultCompanyId();
        try {
            RoleLocalServiceUtil.getRole(companyId, FiltersUtil.ROLE);
            LOG.debug("Role already exists");
        } catch (Exception e) {
            LOG.debug("Role doesn't exist, will create it");
            Date now = new Date();
            
            try {
                long roleId = CounterLocalServiceUtil.increment(Role.class.getName());
                Role role = RoleLocalServiceUtil.createRole(roleId);
                role.setName(FiltersUtil.ROLE);
                role.setTitle(FiltersUtil.ROLE);
                role.setDescription("Autogenerated role from Jobs Board portlet");
                role.setType(RoleConstants.TYPE_REGULAR);
                role.setUserId(UserLocalServiceUtil.getDefaultUserId(companyId));
                role.setCompanyId(companyId);
                role.setClassNameId(ClassNameLocalServiceUtil.getClassNameId(Role.class));
                role.setClassPK(roleId);
                role.setCreateDate(now);
                role.setModifiedDate(now);
                role.persist();
                
                LOG.debug("Role created successfully");
            } catch(Exception ex) {
                LOG.error("Error creating role:", ex);
            }
        }
    }
}
