/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.jobsboard.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Applicant service. Represents a row in the &quot;rivetlogic_jobsboard_Applicant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.jobsboard.model.impl.ApplicantModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.jobsboard.model.impl.ApplicantImpl}.
 * </p>
 *
 * @author joseross
 * @see Applicant
 * @see com.rivetlogic.jobsboard.model.impl.ApplicantImpl
 * @see com.rivetlogic.jobsboard.model.impl.ApplicantModelImpl
 * @generated
 */
public interface ApplicantModel extends BaseModel<Applicant> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a applicant model instance should use the {@link Applicant} interface instead.
	 */

	/**
	 * Returns the primary key of this applicant.
	 *
	 * @return the primary key of this applicant
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this applicant.
	 *
	 * @param primaryKey the primary key of this applicant
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the applicant ID of this applicant.
	 *
	 * @return the applicant ID of this applicant
	 */
	public long getApplicantId();

	/**
	 * Sets the applicant ID of this applicant.
	 *
	 * @param applicantId the applicant ID of this applicant
	 */
	public void setApplicantId(long applicantId);

	/**
	 * Returns the job ID of this applicant.
	 *
	 * @return the job ID of this applicant
	 */
	public long getJobId();

	/**
	 * Sets the job ID of this applicant.
	 *
	 * @param jobId the job ID of this applicant
	 */
	public void setJobId(long jobId);

	/**
	 * Returns the group ID of this applicant.
	 *
	 * @return the group ID of this applicant
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this applicant.
	 *
	 * @param groupId the group ID of this applicant
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this applicant.
	 *
	 * @return the company ID of this applicant
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this applicant.
	 *
	 * @param companyId the company ID of this applicant
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this applicant.
	 *
	 * @return the create date of this applicant
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this applicant.
	 *
	 * @param createDate the create date of this applicant
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this applicant.
	 *
	 * @return the modified date of this applicant
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this applicant.
	 *
	 * @param modifiedDate the modified date of this applicant
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this applicant.
	 *
	 * @return the name of this applicant
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this applicant.
	 *
	 * @param name the name of this applicant
	 */
	public void setName(String name);

	/**
	 * Returns the email of this applicant.
	 *
	 * @return the email of this applicant
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this applicant.
	 *
	 * @param email the email of this applicant
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone of this applicant.
	 *
	 * @return the phone of this applicant
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this applicant.
	 *
	 * @param phone the phone of this applicant
	 */
	public void setPhone(String phone);

	/**
	 * Returns the cv of this applicant.
	 *
	 * @return the cv of this applicant
	 */
	public long getCv();

	/**
	 * Sets the cv of this applicant.
	 *
	 * @param cv the cv of this applicant
	 */
	public void setCv(long cv);

	/**
	 * Returns the info of this applicant.
	 *
	 * @return the info of this applicant
	 */
	@AutoEscape
	public String getInfo();

	/**
	 * Sets the info of this applicant.
	 *
	 * @param info the info of this applicant
	 */
	public void setInfo(String info);

	/**
	 * Returns the status of this applicant.
	 *
	 * @return the status of this applicant
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this applicant.
	 *
	 * @param status the status of this applicant
	 */
	public void setStatus(String status);

	/**
	 * Returns the notes of this applicant.
	 *
	 * @return the notes of this applicant
	 */
	@AutoEscape
	public String getNotes();

	/**
	 * Sets the notes of this applicant.
	 *
	 * @param notes the notes of this applicant
	 */
	public void setNotes(String notes);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Applicant applicant);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Applicant> toCacheModel();

	@Override
	public Applicant toEscapedModel();

	@Override
	public Applicant toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}