/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.rivetlogic.jobsboard.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Job service. Represents a row in the &quot;rivetlogic_jobsboard_Job&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.jobsboard.model.impl.JobModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.jobsboard.model.impl.JobImpl}.
 * </p>
 *
 * @author joseross
 * @see Job
 * @see com.rivetlogic.jobsboard.model.impl.JobImpl
 * @see com.rivetlogic.jobsboard.model.impl.JobModelImpl
 * @generated
 */
public interface JobModel extends BaseModel<Job>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a job model instance should use the {@link Job} interface instead.
	 */

	/**
	 * Returns the primary key of this job.
	 *
	 * @return the primary key of this job
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this job.
	 *
	 * @param primaryKey the primary key of this job
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the job ID of this job.
	 *
	 * @return the job ID of this job
	 */
	public long getJobId();

	/**
	 * Sets the job ID of this job.
	 *
	 * @param jobId the job ID of this job
	 */
	public void setJobId(long jobId);

	/**
	 * Returns the group ID of this job.
	 *
	 * @return the group ID of this job
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this job.
	 *
	 * @param groupId the group ID of this job
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this job.
	 *
	 * @return the company ID of this job
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this job.
	 *
	 * @param companyId the company ID of this job
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this job.
	 *
	 * @return the user ID of this job
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this job.
	 *
	 * @param userId the user ID of this job
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this job.
	 *
	 * @return the user uuid of this job
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this job.
	 *
	 * @param userUuid the user uuid of this job
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this job.
	 *
	 * @return the user name of this job
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this job.
	 *
	 * @param userName the user name of this job
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this job.
	 *
	 * @return the create date of this job
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this job.
	 *
	 * @param createDate the create date of this job
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this job.
	 *
	 * @return the modified date of this job
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this job.
	 *
	 * @param modifiedDate the modified date of this job
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this job.
	 *
	 * @return the name of this job
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this job.
	 *
	 * @param name the name of this job
	 */
	public void setName(String name);

	/**
	 * Returns the active of this job.
	 *
	 * @return the active of this job
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this job is active.
	 *
	 * @return <code>true</code> if this job is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this job is active.
	 *
	 * @param active the active of this job
	 */
	public void setActive(boolean active);

	/**
	 * Returns the category of this job.
	 *
	 * @return the category of this job
	 */
	public long getCategory();

	/**
	 * Sets the category of this job.
	 *
	 * @param category the category of this job
	 */
	public void setCategory(long category);

	/**
	 * Returns the location of this job.
	 *
	 * @return the location of this job
	 */
	public long getLocation();

	/**
	 * Sets the location of this job.
	 *
	 * @param location the location of this job
	 */
	public void setLocation(long location);

	/**
	 * Returns the type of this job.
	 *
	 * @return the type of this job
	 */
	public long getType();

	/**
	 * Sets the type of this job.
	 *
	 * @param type the type of this job
	 */
	public void setType(long type);

	/**
	 * Returns the description of this job.
	 *
	 * @return the description of this job
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this job.
	 *
	 * @param description the description of this job
	 */
	public void setDescription(String description);

	/**
	 * Returns the salary of this job.
	 *
	 * @return the salary of this job
	 */
	public double getSalary();

	/**
	 * Sets the salary of this job.
	 *
	 * @param salary the salary of this job
	 */
	public void setSalary(double salary);

	/**
	 * Returns the bookmarks of this job.
	 *
	 * @return the bookmarks of this job
	 */
	@AutoEscape
	public String getBookmarks();

	/**
	 * Sets the bookmarks of this job.
	 *
	 * @param bookmarks the bookmarks of this job
	 */
	public void setBookmarks(String bookmarks);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Job job);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Job> toCacheModel();

	@Override
	public Job toEscapedModel();

	@Override
	public Job toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}